import "./globals.css";
import type { Metadata } from "next";

import LayoutStoreProvider from "@/app/_layoutStoreComponents/LayoutStoreProvider";
import LayoutStoreButton from "@/app/_layoutStoreComponents/LayoutStoreButton";

import MainLayoutProvider from "@/app/_components/MainLayoutProvider";

import WrapperBox from "@/app/_components/WrapperBox";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  navbar,
}: {
  children: React.ReactNode;
  navbar: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LayoutStoreProvider headerContent={<LayoutStoreButton />}>
          <div className="flex gap-4">
            {navbar}
            <div className="flex-grow">
              <WrapperBox title="Main Layout" type="rsc">
                <MainLayoutProvider>{children}</MainLayoutProvider>
              </WrapperBox>
            </div>
          </div>
        </LayoutStoreProvider>
      </body>
    </html>
  );
}
